#!/usr/bin/env node
// Generates adr/INDEX.md from ADR frontmatter (ADR-0001: every file is immutable or
// generated; this one is generated). It is never hand-edited — the pre-commit hook
// regenerates it and fails if the working copy is stale, so the index cannot drift from
// the corpus it summarises.
//
//   node scripts/build-index.mjs [repo-root]     (default: cwd)  — writes adr/INDEX.md
//   --check                                       — exit 1 if INDEX.md is out of date
//   --stdout                                      — print, don't write
//
// Zero dependencies, plain Node ESM — same rationale as lint-docs.mjs (ADR-0003).

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { loadDocs } from './lint-docs.mjs';

const pad = (v) => String(v).trim().padStart(4, '0');

/** Escape a cell so a title containing `|` cannot break the markdown table. */
const cell = (s) => String(s).replace(/\|/g, '\\|');

/**
 * Builds the INDEX.md text from a repo's ADR corpus. Pure: takes loaded docs, returns a
 * string, touches no filesystem — so the same function serves both write and --check.
 */
export function renderIndex(docs) {
  const adrs = docs
    .filter((d) => d.ok && d.data.id !== undefined)
    .map((d) => ({
      id: pad(d.data.id),
      title: d.data.title ?? '',
      type: d.data.type ?? '',
      status: d.data.status ?? '',
      supersedes: (d.data.supersedes ?? []).map(pad),
      superseded_by: (d.data.superseded_by ?? []).map(pad),
    }))
    .sort((a, b) => a.id.localeCompare(b.id));

  const byType = (t) => adrs.filter((a) => a.type === t);
  const active = (list) => list.filter((a) => a.status !== 'superseded');

  const out = [];
  out.push('# ADR Index');
  out.push('');
  out.push('<!-- GENERATED by scripts/build-index.mjs — do not edit by hand (ADR-0001).');
  out.push('     Regenerate with `npm run index`; the pre-commit hook keeps it current. -->');
  out.push('');
  out.push(`${adrs.length} decision(s): ${byType('architecture').length} architecture, ` +
    `${byType('slice').length} slice, ${byType('batch').length} batch.`);

  const section = (heading, list) => {
    out.push('');
    out.push(`## ${heading}`);
    out.push('');
    if (!list.length) {
      out.push('_None._');
      return;
    }
    out.push('| id | title | status |');
    out.push('| --- | --- | --- |');
    for (const a of list) {
      out.push(`| ${a.id} | ${cell(a.title)} | ${a.status} |`);
    }
  };

  section('Architecture', active(byType('architecture')));
  section('Slices', active(byType('slice')));
  const batches = active(byType('batch'));
  if (batches.length) section('Batches', batches);

  // Supersession graph — every edge, derived from superseded_by. Rule 4 guarantees these
  // are bidirectional in a green corpus, so one direction is enough to draw the graph.
  const edges = [];
  for (const a of adrs) {
    for (const target of a.superseded_by) edges.push([a.id, target]);
  }
  edges.sort((x, y) => x[0].localeCompare(y[0]) || x[1].localeCompare(y[1]));

  out.push('');
  out.push('## Supersession');
  out.push('');
  if (!edges.length) {
    out.push('_None._');
  } else {
    const titleOf = new Map(adrs.map((a) => [a.id, a.title]));
    for (const [from, to] of edges) {
      out.push(`- ${from} → ${to}  (${cell(titleOf.get(to) ?? 'unknown')})`);
    }
  }

  out.push('');
  return out.join('\n');
}

function indexPath(root) {
  const dir = ['adr', 'slices'].map((d) => join(root, d)).find(existsSync) ?? join(root, 'adr');
  return join(dir, 'INDEX.md');
}

function main(argv) {
  const check = argv.includes('--check');
  const toStdout = argv.includes('--stdout');
  const root = argv.find((a) => !a.startsWith('--')) ?? process.cwd();

  const text = renderIndex(loadDocs(root));
  const path = indexPath(root);

  if (toStdout) {
    process.stdout.write(text);
    return 0;
  }

  if (check) {
    const current = existsSync(path) ? readFileSync(path, 'utf8') : '';
    if (current !== text) {
      console.error(`${path} is out of date — run \`npm run index\` and commit the result.`);
      return 1;
    }
    return 0;
  }

  writeFileSync(path, text);
  console.log(`wrote ${path}`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exit(main(process.argv.slice(2)));
}
