"""PlatformIO pre-build hook: embed a real handshake pcap for the on-air upload verify.

The slice-0018 verify normally injects a *synthetic* handshake, which wpa-sec rejects — that still
proves the TLS-pin/POST/parse/resume path, but never exercises the accepted/duplicate→delete branch
against the live service. To exercise it, point SAPPER_TEST_UPLOAD_PCAP at a real captured `.pcap`
(e.g. one of the operator's own captures); this hook reads that file and generates
`src/gen/wpasec_test_pcap.h` with its bytes, which the upload probe injects instead of the synthetic.

The file is read from the operator's environment, never committed — `src/gen/` is gitignored — so no
real handshake (someone's network) ends up in the repo, and only a testhooks build with the variable
set embeds one. When the variable is unset the generated array is empty and the probe falls back to the
synthetic stimulus, so the build still succeeds with no capture present.
"""
import os

Import("env")  # noqa: F821 — provided by the PlatformIO build runner.

project_dir = env["PROJECT_DIR"]  # noqa: F821
gen_dir = os.path.join(project_dir, "src", "gen")
os.makedirs(gen_dir, exist_ok=True)
out_path = os.path.join(gen_dir, "wpasec_test_pcap.h")

pcap_path = os.environ.get("SAPPER_TEST_UPLOAD_PCAP", "").strip()
data = b""
if pcap_path:
    if not os.path.isfile(pcap_path):
        raise SystemExit(
            "SAPPER_TEST_UPLOAD_PCAP is set but not a readable file: %r" % pcap_path
        )
    with open(pcap_path, "rb") as handle:
        data = handle.read()
    if not data:
        raise SystemExit("SAPPER_TEST_UPLOAD_PCAP file is empty: %r" % pcap_path)

lines = [
    "// Generated by scripts/embed_test_pcap.py — do not edit, do not commit (src/gen/ is gitignored).",
    "#pragma once",
    "",
    "#include <cstddef>",
    "#include <cstdint>",
    "",
    "namespace sapper {",
    "",
]
if data:
    body = ", ".join("0x%02x" % b for b in data)
    lines.append("inline constexpr unsigned char kWpaSecTestPcap[] = {%s};" % body)
    lines.append("inline constexpr size_t kWpaSecTestPcapLen = %d;" % len(data))
else:
    # No file given: an empty stimulus. The probe checks the length and falls back to synthetic.
    lines.append("inline constexpr unsigned char kWpaSecTestPcap[] = {0x00};")
    lines.append("inline constexpr size_t kWpaSecTestPcapLen = 0;")
lines += ["", "}  // namespace sapper", ""]

with open(out_path, "w") as handle:
    handle.write("\n".join(lines))

print("[embed_test_pcap] wrote %s (%d bytes embedded)" % (out_path, len(data)))
